name: build-cpu-docker
on:
  push:
    branches:
      - linux-shared
  workflow_dispatch:

concurrency:
  group: build-cpu-docker-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-cpu-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free space
        shell: bash
        run: |
          df -h
          rm -rf /opt/hostedtoolcache
          df -h

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout pypa/manylinux
        uses: actions/checkout@v4
        with:
          repository: pypa/manylinux
          submodules: true
          ref: 5eda9aded5462201e6310105728d33016e637ea7

      - name: Build docker Image
        shell: bash
        run: |
          git clone https://github.com/pypa/manylinux
          cd manylinux/
          git checkout 5eda9aded5462201e6310105728d33016e637ea7
          cd ..

          cp .github/docker/Dockerfile.manylinux2014_cpu manylinux/docker/Dockerfile

          tag=ghcr.io/${{ github.repository_owner }}/onnxruntime-libs:manylinux2014-x86_64-cpu
          echo "tag: $tag"

          cd manylinux/docker/Dockerfile

          docker build \
            -t $tag \
            .

          docker image ls
          docker push $tag
