name: linux-x64-static

on:
  push:
    branches:
      - master
      - linux-static
    paths:
      - '.github/workflows/linux-x64-static.yaml'

  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/linux-x64-static.yaml'

  workflow_dispatch:
    inputs:
      version:
        description: "Version information（e.g., 1.15.1）"
        required: true

permissions:
  contents: write

env:
  ONNXRUNTIME_VERSION:
    |- # Enter release tag name or version name in workflow_dispatch. Appropriate version if not specified
    ${{ github.event.release.tag_name || github.event.inputs.version || '1.15.1' }}

jobs:
  Linux_x64_static:
    name: Linux x64 static
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache build result for ${{ env.ONNXRUNTIME_VERSION }}
        id: cache-build-result
        uses: actions/cache@v2
        with:
          path: onnxruntime-linux-x64-static-${{ env.ONNXRUNTIME_VERSION }}
          key: onnxruntime-linux-x64-static-${{ env.ONNXRUNTIME_VERSION }}-cache-v1

      - name: Checkout
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: microsoft/onnxruntime
          submodules: true
          ref: v${{ env.ONNXRUNTIME_VERSION }}

      - name: Download protoc
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          # see ./cmake/deps.txt
          if [[ ${{ env.ONNXRUNTIME_VERSION }} =~ 1.14.[0-9] ]]; then
            wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip
            unzip protoc-3.20.3-linux-x86_64.zip
          elif [[ ${{ env.ONNXRUNTIME_VERSION }} =~ 1.15.[0-9] ]]; then
            wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
            unzip protoc-21.12-linux-x86_64.zip
          else
            echo "Unsupported version ${{ env.ONNXRUNTIME_VERSION }}"
            exit 1
          fi

          ./bin/protoc --version

      - name: Set environment variable
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "$GITHUB_WORKSPACE/bin"  >> "$GITHUB_PATH"

      - name: Display protoc info for ${{ env.ONNXRUNTIME_VERSION }}
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          protoc --version

      - name: Show current directory
        shell: bash
        run: |
          ls -lh
          echo $PWD

      - name: Install dependencies
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install python3 git-lfs
          python3 -m pip install cmake
          cmake --version

      - name: Build static onnxruntime for Linux x64
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          build_dir=./build-linux-x64-static

          python3 ./tools/ci_build/build.py \
            --build_dir $build_dir \
            --config Release \
            --build \
            --update \
            --path_to_protoc_exe $GITHUB_WORKSPACE/bin/protoc \
            --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF \
            --cmake_extra_defines CMAKE_INSTALL_PREFIX=$build_dir/install/ \
            --target install \
            --parallel \
            --skip_tests

      - name: Display libraries
        # if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          find ./build-linux-x64-static -name "lib*.a"

      - name: Display build results
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          tree ./build-linux-x64-static

      - name: Collect results
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          build_dir=./build-linux-x64-static
          version=${{ env.ONNXRUNTIME_VERSION }}

          dst_dir=onnxruntime-linux-x64-static-$version

          mkdir $dst_dir
          mkdir $dst_dir/lib
          mkdir $dst_dir/include

          echo "copy libs"
          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/base/libabsl_base.a $dst_dir/lib
          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/base/libabsl_raw_logging_internal.a $dst_dir/lib
          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/base/libabsl_throw_delegate.a $dst_dir/lib

          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/hash/libabsl_city.a $dst_dir/lib
          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/hash/libabsl_hash.a $dst_dir/lib
          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/hash/libabsl_low_level_hash.a $dst_dir/lib

          cp -v $build_dir/Release/_deps/abseil_cpp-build/absl/container/libabsl_raw_hash_set.a $dst_dir/lib

          cp -v $build_dir/Release/_deps/flatbuffers-build/libflatbuffers.a $dst_dir/lib

          cp -v $build_dir/Release/_deps/onnx-build/libonnx_proto.a $dst_dir/lib
          cp -v $build_dir/Release/_deps/onnx-build/libonnx.a $dst_dir/lib

          cp -v $build_dir/Release/libonnxruntime_common.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_flatbuffers.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_framework.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_graph.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_mlas.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_optimizer.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_providers.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_session.a $dst_dir/lib
          cp -v $build_dir/Release/libonnxruntime_util.a $dst_dir/lib

          cp -v $build_dir/Release/_deps/protobuf-build/libprotobuf-lite.a $dst_dir/lib

          echo "copy headers"

          cp ./include/onnxruntime/core/providers/cpu/cpu_provider_factory.h $dst_dir/include/
          cp ./include/onnxruntime/core/session/onnxruntime_c_api.h $dst_dir/include
          cp ./include/onnxruntime/core/session/onnxruntime_cxx_api.h $dst_dir/include
          cp ./include/onnxruntime/core/session/onnxruntime_cxx_inline.h $dst_dir/include
          cp ./include/onnxruntime/core/session/onnxruntime_run_options_config_keys.h $dst_dir/include
          cp ./include/onnxruntime/core/session/onnxruntime_session_options_config_keys.h $dst_dir/include
          cp ./include/onnxruntime/core/framework/provider_options.h $dst_dir/include
          cp ./include/onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.h $dst_dir/include

          tree $dst_dir

      - name: Upload artifact
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: onnxruntime-linux-x64-static-${{ env.ONNXRUNTIME_VERSION }}
          path: onnxruntime-linux-x64-static-${{ env.ONNXRUNTIME_VERSION }}

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: github.repository_owner == 'csukuangfj' && steps.cache-build-result.outputs.cache-hit != 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        shell: bash
        run: |
          ls -lh
          version=${{ env.ONNXRUNTIME_VERSION }}

          tree ./onnxruntime-linux-x64-static-$version/

          zip -r onnxruntime-linux-x64-static-${version}.zip ./onnxruntime-linux-x64-static-$version/

          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/onnxruntime-libs huggingface

          cd huggingface
          git lfs pull
          cp -v ../onnxruntime-linux-x64-static-*.zip ./
          git status
          git lfs track "*.zip"

          git add .

          git commit -m "upload onnxruntime-linux-x64-static-${{ env.ONNXRUNTIME_VERSION }}.zip"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/onnxruntime-libs main


